// src/elevator-react/configurator.component.jsx

import { Component } from 'react';
import { ConfigStore } from '../elevator/config-store';
import { FormCapacity } from './form-capacity.component';
import { FormDimensions } from './form-dimensions.component';
import { Summary } from './summary.component';

export class Configurator extends Component {

    constructor() {
        super();
        this.configStore = new ConfigStore();
        this.state = {
            config: this.configStore.getConfig()
        };

    }

    updateConfig(config) {
        this.configStore.updateConfig(config);
        this.setState({config: this.configStore.getConfig()});
    }

    render() {
        return <div>
            <h1>React</h1>
            <FormCapacity
                config={this.state.config}
                onConfigUpdate={this.updateConfig.bind(this)}/>
            <FormDimensions
                config={this.state.config}
                onConfigUpdate={this.updateConfig.bind(this)}/>
            <Summary
                config={this.state.config}/>
        </div>;
    }

}

// src/elevator-angular/configurator.component.ts
/**
 *
 * (c) 2013-2017 Wishtack
 *
 * $Id: $
 */

import { Component } from '@angular/core';
import { ConfigStore } from '../elevator/config-store';

@Component({
    selector: 'wt-configurator',
    template: `
<h1>Angular</h1>
<wt-form-capacity
        [config]="getConfig()"
        (onConfigChange)="updateConfig($event)"></wt-form-capacity>
<wt-form-dimensions
        [config]="getConfig()"
        (onConfigChange)="updateConfig($event)"></wt-form-dimensions>
<wt-summary
        [config]="getConfig()"></wt-summary>
`
})
export class ConfiguratorComponent {

    private _configStore = new ConfigStore();

    getConfig() {
        return this._configStore.getConfig();
    }

    updateConfig(config) {
        this._configStore.updateConfig(config);
    }

}
